name: Python Module CI and Docker build.
on:
  release: 
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
        
      - name: Install Dependancies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install setuptools build
          pip install -r requirements.txt
      
      - name: Parse the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build Package
        run: |
          echo "${{steps.vars.outputs.tag}}" > VERSION
          python -m build
      
      - name: Publish Package to Pypi
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}